FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    openssl \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Enable Yarn
RUN corepack enable && corepack prepare yarn@1.22.22 --activate

# Install deps FIRST
COPY package.json yarn.lock ./
RUN yarn install

# Prisma
COPY prisma ./prisma
RUN npx prisma generate

# Copy rest of source
COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]
