openapi: 3.0.0
info:
  title: Scoutproperties API
  version: 1.0.0
  description: API documentation for Scoutproperties
servers:
  - url: http://localhost:3000
tags:
  - name: Auth
    description: Authentication endpoints
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
  /api/auth/login:
    post:
      summary: Log in a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
  /api/auth/logout:
    post:
      summary: Log out a user
      tags: [Auth]
      responses:
        '200':
          description: User logged out successfully
